version: '2'
services:
  app:
    container_name: meetapp
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: yarn dev
    ports:
      - '3333:3333'
    links:
      - mongo
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - MONGO_HOST=mongo
      - REDIS_HOST=redis
    env_file:
      - .env

  mongo:
    container_name: meetapp-mongo
    image: mongo
    volumes:
      - ./data:/data/mongo
    ports:
      - '27017:27017'
  postgres:
    container_name: meetapp-postgres
    image: postgres
    volumes:
      - ./data:/data/postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

  redis:
    container_name: meetapp-redis
    image: redis:alpine
    ports:
      - '6379:6379'

volumes:
  data:
